services:
  redis-taskiq:
    image: redis:8.4-alpine
    command:
      [
        "redis-server",
        "--appendonly",
        "yes",
        "--appendfsync",
        "everysec",
        "--maxmemory-policy",
        "noeviction",
      ]
    volumes:
      - taskome_redis_taskiq_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped

  redis-rate-limit:
    image: redis:8.4-alpine
    command:
      [
        "redis-server",
        "--save",
        "",
        "--appendonly",
        "no",
        "--maxmemory",
        "128mb",
        "--maxmemory-policy",
        "volatile-ttl",
      ]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped

volumes:
  taskome_redis_taskiq_data:
