/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as AuthIndexRouteImport } from './routes/_auth/index'
import { Route as AuthProjectsRouteImport } from './routes/_auth/projects'
import { Route as AuthSettingsRouteRouteImport } from './routes/_auth/settings/route'
import { Route as AuthSettingsIndexRouteImport } from './routes/_auth/settings/index'
import { Route as AuthSettingsApiKeysRouteImport } from './routes/_auth/settings/api-keys'
import { Route as AuthSettingsProfileRouteImport } from './routes/_auth/settings/profile'
import { Route as AuthSettingsSecurityRouteImport } from './routes/_auth/settings/security'
import { Route as AuthUtilitiesStructureViewerRouteImport } from './routes/_auth/utilities/structure-viewer'

const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthProjectsRoute = AuthProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSettingsRouteRoute = AuthSettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSettingsIndexRoute = AuthSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthSettingsRouteRoute,
} as any)
const AuthSettingsApiKeysRoute = AuthSettingsApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => AuthSettingsRouteRoute,
} as any)
const AuthSettingsProfileRoute = AuthSettingsProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthSettingsRouteRoute,
} as any)
const AuthSettingsSecurityRoute = AuthSettingsSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AuthSettingsRouteRoute,
} as any)
const AuthUtilitiesStructureViewerRoute =
  AuthUtilitiesStructureViewerRouteImport.update({
    id: '/utilities/structure-viewer',
    path: '/utilities/structure-viewer',
    getParentRoute: () => AuthRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthIndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/settings': typeof AuthSettingsRouteRouteWithChildren
  '/projects': typeof AuthProjectsRoute
  '/settings/api-keys': typeof AuthSettingsApiKeysRoute
  '/settings/profile': typeof AuthSettingsProfileRoute
  '/settings/security': typeof AuthSettingsSecurityRoute
  '/utilities/structure-viewer': typeof AuthUtilitiesStructureViewerRoute
  '/settings/': typeof AuthSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/projects': typeof AuthProjectsRoute
  '/': typeof AuthIndexRoute
  '/settings/api-keys': typeof AuthSettingsApiKeysRoute
  '/settings/profile': typeof AuthSettingsProfileRoute
  '/settings/security': typeof AuthSettingsSecurityRoute
  '/utilities/structure-viewer': typeof AuthUtilitiesStructureViewerRoute
  '/settings': typeof AuthSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_auth/settings': typeof AuthSettingsRouteRouteWithChildren
  '/_auth/projects': typeof AuthProjectsRoute
  '/_auth/': typeof AuthIndexRoute
  '/_auth/settings/api-keys': typeof AuthSettingsApiKeysRoute
  '/_auth/settings/profile': typeof AuthSettingsProfileRoute
  '/_auth/settings/security': typeof AuthSettingsSecurityRoute
  '/_auth/utilities/structure-viewer': typeof AuthUtilitiesStructureViewerRoute
  '/_auth/settings/': typeof AuthSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/settings'
    | '/projects'
    | '/settings/api-keys'
    | '/settings/profile'
    | '/settings/security'
    | '/utilities/structure-viewer'
    | '/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/signup'
    | '/projects'
    | '/'
    | '/settings/api-keys'
    | '/settings/profile'
    | '/settings/security'
    | '/utilities/structure-viewer'
    | '/settings'
  id:
    | '__root__'
    | '/_auth'
    | '/login'
    | '/signup'
    | '/_auth/settings'
    | '/_auth/projects'
    | '/_auth/'
    | '/_auth/settings/api-keys'
    | '/_auth/settings/profile'
    | '/_auth/settings/security'
    | '/_auth/utilities/structure-viewer'
    | '/_auth/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/': {
      id: '/_auth/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/projects': {
      id: '/_auth/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AuthProjectsRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/settings': {
      id: '/_auth/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthSettingsRouteRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/settings/': {
      id: '/_auth/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthSettingsIndexRouteImport
      parentRoute: typeof AuthSettingsRouteRoute
    }
    '/_auth/settings/api-keys': {
      id: '/_auth/settings/api-keys'
      path: '/api-keys'
      fullPath: '/settings/api-keys'
      preLoaderRoute: typeof AuthSettingsApiKeysRouteImport
      parentRoute: typeof AuthSettingsRouteRoute
    }
    '/_auth/settings/profile': {
      id: '/_auth/settings/profile'
      path: '/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof AuthSettingsProfileRouteImport
      parentRoute: typeof AuthSettingsRouteRoute
    }
    '/_auth/settings/security': {
      id: '/_auth/settings/security'
      path: '/security'
      fullPath: '/settings/security'
      preLoaderRoute: typeof AuthSettingsSecurityRouteImport
      parentRoute: typeof AuthSettingsRouteRoute
    }
    '/_auth/utilities/structure-viewer': {
      id: '/_auth/utilities/structure-viewer'
      path: '/utilities/structure-viewer'
      fullPath: '/utilities/structure-viewer'
      preLoaderRoute: typeof AuthUtilitiesStructureViewerRouteImport
      parentRoute: typeof AuthRouteRoute
    }
  }
}

interface AuthSettingsRouteRouteChildren {
  AuthSettingsApiKeysRoute: typeof AuthSettingsApiKeysRoute
  AuthSettingsProfileRoute: typeof AuthSettingsProfileRoute
  AuthSettingsSecurityRoute: typeof AuthSettingsSecurityRoute
  AuthSettingsIndexRoute: typeof AuthSettingsIndexRoute
}

const AuthSettingsRouteRouteChildren: AuthSettingsRouteRouteChildren = {
  AuthSettingsApiKeysRoute: AuthSettingsApiKeysRoute,
  AuthSettingsProfileRoute: AuthSettingsProfileRoute,
  AuthSettingsSecurityRoute: AuthSettingsSecurityRoute,
  AuthSettingsIndexRoute: AuthSettingsIndexRoute,
}

const AuthSettingsRouteRouteWithChildren =
  AuthSettingsRouteRoute._addFileChildren(AuthSettingsRouteRouteChildren)

interface AuthRouteRouteChildren {
  AuthSettingsRouteRoute: typeof AuthSettingsRouteRouteWithChildren
  AuthProjectsRoute: typeof AuthProjectsRoute
  AuthIndexRoute: typeof AuthIndexRoute
  AuthUtilitiesStructureViewerRoute: typeof AuthUtilitiesStructureViewerRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthSettingsRouteRoute: AuthSettingsRouteRouteWithChildren,
  AuthProjectsRoute: AuthProjectsRoute,
  AuthIndexRoute: AuthIndexRoute,
  AuthUtilitiesStructureViewerRoute: AuthUtilitiesStructureViewerRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthRouteRoute: AuthRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
