[project]
name = "fpocket-runtime"
version = "0.0.0"
description = "Taskome Tool Runtime for fpocket"
authors = [{ name = "ukeSJTU", email = "uke_sjtu@sjtu.edu.cn" }]
requires-python = ">=3.14"
dependencies = ["runtime-toolkit"]

[build-system]
requires = ["uv_build>=0.12.1,<0.13.0"]
build-backend = "uv_build"

[tool.uv.sources]
runtime-toolkit = { workspace = true }
